<?php

namespace Knws\PortfolioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function showStuff($id)
    {
        /*
        $em = $this->getDoctrine()->getManager();
        $query = $em->createQuery(
            'SELECT p FROM KnwsPortfolioBundle:Product p WHERE p.price > :price ORDER BY p.price ASC'
        )->setParameter('price', '19.99');

        $products = $query->getResult();*/
    }

    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM KnwsPortfolioBundle:Product p ORDER BY p.name ASC')
            ->getResult();
    }
}
