<?php

namespace Knws\PortfolioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WorkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkRepository extends EntityRepository
{
    public function frontpage()
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT w FROM KnwsPortfolioBundle:Work w ORDER BY w.id DESC'
            );

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function work($slug)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT w FROM KnwsPortfolioBundle:Work w WHERE w.slug = :slug'
            )->setParameter('slug', $slug);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function getNextPrev()
    {

    }
}
