parameters:
    database_driver: pdo_mysql
    database_host: 91.239.233.79
    database_port: null
    database_name: portfolio
    database_user: paranoid
    database_password: bCQT5mDDCJqq6zHlrjt6
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: f639c0a958fab57bf85b3a16cbc064522511dc8a
    database_path: null
