knws_portfolio_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: KnwsPortfolioBundle:Default:index }

knws_portfolio_works:
    pattern:  /works
    defaults: { _controller: KnwsPortfolioBundle:Works:index }

knws_portfolio_products:
    pattern:  /prod
    defaults: { _controller: KnwsPortfolioBundle:Default:create }

knws_portfolio_products_show:
    pattern:  /prod/{id}
    defaults: { _controller: KnwsPortfolioBundle:Default:show }

knws_portfolio_products_repo:
    pattern:  /repo
    defaults: { _controller: KnwsPortfolioBundle:Default:repo }

knws_portfolio_products_create:
    pattern:  /create
    defaults: { _controller: KnwsPortfolioBundle:Default:createProduct }