knws_portfolio_homepage:
    pattern:  /
    defaults: { _controller: KnwsPortfolioBundle:Works:index }

knws_portfolio_works:
    pattern:  /works
    defaults: { _controller: KnwsPortfolioBundle:Works:index }

knws_portfolio_work:
    pattern:  /project/{slug}
    defaults: { _controller: KnwsPortfolioBundle:Works:work }
    requirements:
      slug: "[a-zA-Z]+"