knws_portfolio_homepage:
    pattern:  /
    defaults: { _controller: KnwsPortfolioBundle:Works:index }

knws_portfolio_works:
    pattern:  /works
    defaults: { _controller: KnwsPortfolioBundle:Works:index }

knws_portfolio_works_new:
    pattern:  /works/new
    defaults: { _controller: KnwsPortfolioBundle:Works:new }

knws_portfolio_work:
    pattern:  /works/{slug}
    defaults: { _controller: KnwsPortfolioBundle:Works:work }
    requirements:
      slug: "[a-zA-Z]+"

knws_portfolio_services:
    pattern:  /services
    defaults: { _controller: KnwsPortfolioBundle:Content:services }

knws_portfolio_skills:
    pattern:  /skills
    defaults: { _controller: KnwsPortfolioBundle:Content:skills }

knws_portfolio_contacts:
    pattern:  /contacts
    defaults: { _controller: KnwsPortfolioBundle:Content:contacts }

knws_logout:
    pattern:  /logout
    defaults: { _controller: KnwsPortfolioBundle:Secured:logout }

knws_login_check:
    pattern:  /login_check
    defaults: { _controller: KnwsPortfolioBundle:Secured:loginCheck }

knws_login:
    pattern:  /login
    defaults: { _controller: KnwsPortfolioBundle:Secured:login }
