parameters:
#    knws_portfolio.example.class: Knws\PortfolioBundle\Example

services:
#    knws_portfolio.example:
#        class: %knws_portfolio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
